spring.application.name=pooler-backend

# Datasource
spring.datasource.url = jdbc:h2:mem:poolerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username =sa
spring.datasource.password=password

#H2 Console
spring.h2.console.enabled=true
spring.h2.console.path= /h2-console

#hibernate
spring.jpa.hibernate.ddl-auto =create-drop
spring.jpa.show-sql= true

#Mail Sender
spring.mail.host= smtp.gmail.com
spring.mail.port=587
spring.mail.username= dev@enterprise.com
spring.mail.password= dev-password
