create table pb_refresh_token (
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        ip_address varchar(45),
        app_version varchar(50),
        platform varchar(50),
        device_id varchar(200),
        refresh_token varchar(512) not null unique,
        entity_id varchar(255) not null,
        status enum ('ACTIVE','EXPIRED','REVOKED','USED') not null,
        primary key (id)
    )

    create table pb_refresh_token (
            is_active boolean not null,
            created_at timestamp(6) with time zone not null,
            expires_at timestamp(6) with time zone not null,
            id bigint generated by default as identity,
            updated_at timestamp(6) with time zone not null,
            ip_address varchar(45),
            app_version varchar(50),
            platform varchar(50),
            device_id varchar(200),
            refresh_token varchar(512) not null unique,
            entity_id varchar(255) not null,
            status enum ('ACTIVE','EXPIRED','REVOKED','USED') not null,
            primary key (id)
        )

         create table pb_user (
                is_active boolean not null,
                created_at timestamp(6) with time zone not null,
                id bigint generated by default as identity,
                updated_at timestamp(6) with time zone not null,
                session_id varchar(64) not null,
                email varchar(255),
                entity_id varchar(255),
                name varchar(255),
                username varchar(255),
                primary key (id),
                unique (username),
                unique (email)
            )

            create table pb_user (
                    is_active boolean not null,
                    created_at timestamp(6) with time zone not null,
                    id bigint generated by default as identity,
                    updated_at timestamp(6) with time zone not null,
                    session_id varchar(64) not null,
                    email varchar(255),
                    entity_id varchar(255),
                    name varchar(255),
                    username varchar(255),
                    primary key (id),
                    unique (username),
                    unique (email)
                )


